### ISSUE TITLE
fcli ssc appversion-artifact download: response 500 returned when --no-include-source is used without --id

### ISSUE THREAD

**Issue by james-du1** [fortify-ps/fcli#173]
according to document of fcli tool
--no-include-sources, --id=<artifactId> are mutually exclusive (specify only one) 
but IF --id is NOT included in the command, response 500 returned

in ssc, we can download the snapshot of the application as well as downloading each fpr that was uploaded to the application version, can we replicate the way SSC works so that the functions of fcli tool are aligned with SSC?

![image](https://user-images.githubusercontent.com/120057653/206587395-4c0f0857-0f36-45ae-a082-e1fa87abe9fb.png)

**Comment by rsenden** [comment]
The `--no-include-sources` option is only applicable when downloading the latest application state for the given application version, not when downloading an artifact by id (since that will be the original artifact), hence those two options are mutually exclusive. Question is why this results in an HTTP 500 error; can you check/share the SSC logs?

**Comment by wtfacoconut** [comment]
Hey @rsenden , I think James might be correct in that the `--id` and `--no-include-sources` options needing to not be mutually exclusive. Looking at the SSC web UI, it appears that you can download previously uploaded artifacts with/without sources.
![image](https://user-images.githubusercontent.com/5297545/207170411-b2ee08cd-cf1e-4919-bd9c-28bd9253d29a.png)

These are the API's that I'm seeing being invoked when trying to download an artifact with/without sources, versus downloading an "application version state" artifact with/without sources.
![image](https://user-images.githubusercontent.com/5297545/207172985-6a4a38ec-5d49-4222-b707-b7092b7306c2.png)

**Comment by rsenden** [comment]
There was actually another bug in the download command, with application file downloads (no `--id` specified on command line) always failing and the `--id` option downloading the application file instead of the requested id due to inverted logic. Next push will fix this, and will also have the `--no-include-sources` option available for both raw FPR and application file downloads.
