### ISSUE TITLE
fcli ssc token list -u user -p pass --url url -> remaining usage -1 // MAC

### ISSUE THREAD

**Issue by xakrurychle** [fortify-ps/fcli#194]
![Screenshot 2022-12-14 at 12 38 42](https://user-images.githubusercontent.com/63144637/207585505-39156758-9808-439b-95c3-50a6e58e9016.png)

remaining usage appears to be -1 though in SSC its like this
![Screenshot 2022-12-14 at 12 39 48](https://user-images.githubusercontent.com/63144637/207585716-09e852e7-9cea-4bf5-81de-2f2b840f6446.png)

**Comment by rsenden** [comment]
SSC 'Days to Expiration' corresponds to the token terminal date as displayed by SSC. Apparently, the SSC backend additionally allows for having tokens that can be used only a certain number of times (independent of expiration date), with `-1` indicating that the token can be used for an unlimited amount of times. Since this information is not displayed in SSC, we should probably remove it from fcli (table) output as well to avoid confusion.

**Comment by xakrurychle** [comment]
retested on v1.0.1, fixed
