### ISSUE TITLE
fcli ssc app get --session session  {?varName:attrName} -> variable not picked in zsh // MAC

### ISSUE THREAD

**Issue by xakrurychle** [fortify-ps/fcli#208]
to be able to use a saved variable in another command the user has to switch to bash
![Screenshot 2022-12-19 at 15 46 02](https://user-images.githubusercontent.com/63144637/208451979-f27d9173-2793-4786-97d8-68907788097a.png)
![Screenshot 2022-12-19 at 15 46 25](https://user-images.githubusercontent.com/63144637/208452060-5b4d7ffe-4a0c-4698-bac6-450cf90ea37a.png)

**Comment by rsenden** [comment]
Apparently, `{?id:id}` is interpreted by zsh instead of being passed to fcli. We already have some information about properly quoting/escaping the `?` variable (see https://fortify-ps.github.io/fcli/#fcli-variables), we should probably update this information to state that on some shells, named variable references like in this example may also need to be quoted/escaped. On zsh, I guess things will work fine if you use single quotes around `'{?id:id}'`, can you verify?

**Comment by xakrurychle** [comment]
> Apparently, `{?id:id}` is interpreted by zsh instead of being passed to fcli. We already have some information about properly quoting/escaping the `?` variable (see https://fortify-ps.github.io/fcli/#fcli-variables), we should probably update this information to state that on some shells, named variable references like in this example may also need to be quoted/escaped. On zsh, I guess things will work fine if you use single quotes around `'{?id:id}'`, can you verify?

yes it workes with '{?id:id}'

**Comment by rsenden** [comment]
Updated documentation to indicate that named variable references may also need to be quoted/escaped: https://fortify-ps.github.io/fcli/#fcli-variables
